spring:
  application:
    name: ochestration

server:
  port: ${SERVER_PORT}

gateway:
  toss-test:
    base-url: ${TOSS_TEST_BASE_URL}
    secret-key: ${TOSS_TEST_SECRET_KEY}
    connect-timeout-ms: ${PG_CONNECT_TIMEOUT_MS}
    read-timeout-ms: ${PG_READ_TIMEOUT_MS}
